server:
  port: 10000

#JDBC
#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@//localhost:1521/XE
#    username: hr
#    password: 1234

# mybatis
spring:
  datasource:
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@//localhost:1521/XE
      username: hr
      password: 1234
  ssl:
    enabled: true
  mvc:
    cors:
      mappings:
        "/**":
          allowed-origins: "http://localhost:3000"
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: true
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "1073996435598-8scceuhkshjliis09nklkilmjg1nnnqm.apps.googleusercontent.com"
            client-secret: "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"
            redirect-uri: "http://localhost:10000/login/oauth2/code/google"
            scope:
              - email
              - profile
              - openid
            authorization-grant-type: authorization_code
            client-name: google
            provider: google
          naver:
            client-id: "x06ciU7gTmn4AdDnlIn9"
            client-secret: "72JVBavC2E"
            redirect-uri: "http://localhost:10000/login/oauth2/code/naver"
            scope:
              - email
              - name
            authorization-grant-type: authorization_code
            client-name: naver
            provider: naver
          kakao:
            client-id: "3057b78fd96303ba3b717707d305fd52"
            redirect-uri: "http://localhost:10000/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            authorization-grant-type: authorization_code
            client-name: kakao
            provider: kakao
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: name
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: "personalnalbuddybuddy123123lululala456456"

api:
  base-url: "https://apis.data.go.kr/B551011/KorPetTourService"
  base-url2: "https://api.odcloud.kr/api"
  congestion-20171231: "/15071311/v1/uddi:a5158b81-27c7-4151-ba6c-b912a6f13d39"
  area-based-List: "/areaBasedList"
  service-key: "O7M3ojfsc5EkSltlZ1WGlpY1EwcPC%2FtTrzFafZIU0%2F57p9osynNDFH0f55Sg4hiFwkkFvAowoYoDhcQuKUCMbQ%3D%3D"



